version: '3'
services:
  neo4j:
    image: neo4j:5.1.0-enterprise
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      NEO4J_dbms_databases_seed__from__uri__providers: URLConnectionSeedProvider
    volumes:
      - "./backups:/backups"