version: '3'
services:
  neo4j:
    image: neo4j:5.1.0-enterprise
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      # server.memory.heap.max_size=512m
      NEO4J_server_memory_heap_max__size: "4096m"
    volumes:
      - "./conf:/var/lib/neo4j/conf"
  


# docker exec -it 06-configuring-neo4j-neo4j-1 sh